# Nome do Workflow
name: Continuous Integration

# Gatilhos (Triggers)
on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      oracle-db:
        image: gvenzl/oracle-xe:21-slim-faststart
        env:
          ORACLE_PASSWORD: test_password # Senha do SYSTEM, necessária para o healthcheck e admin
          APP_USER: test_user # Usuário dedicado para a aplicação durante os testes
          APP_USER_PASSWORD: test_user_password # Senha do usuário da aplicação
        ports:
          - 1521:1521
        options: >-
          --health-cmd "sqlplus -S system/test_password@//localhost:1521/XEPDB1 <<< \"select 1 from dual;\""
          --health-interval 20s
          --health-start-period 120s
          --health-timeout 10s
          --health-retries 10

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Run Unit and Integration Tests
        run: mvn -B test
        env:
          # Conecta ao banco usando o usuário da aplicação, não o SYSTEM
          DB_URL: jdbc:oracle:thin:@//localhost:1521/XEPDB1
          DB_USERNAME: test_user
          DB_PASSWORD: test_user_password
          JWT_SECRET: jwt-secret-para-testes-de-ci