name: Continuous Delivery

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/micronectar-api:${{ github.sha }}

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    if: github.ref == 'refs/heads/develop'
    environment:
      name: staging
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Staging App Settings
        uses: azure/cli@v1
        with:
          inlineScript: |
            az webapp config appsettings set --resource-group rg-micronectar-devops --name 'app-micronectar-staging' --settings \
              "WEBSITES_PORT=8080" \
              "SPRING_PROFILES_ACTIVE=staging" \
              "DB_URL=${{ secrets.DB_URL_STAGING }}" \
              "DB_USERNAME=${{ secrets.DB_USERNAME_STAGING }}" \
              "DB_PASSWORD=${{ secrets.DB_PASSWORD_STAGING }}" \
              "JWT_SECRET=${{ secrets.JWT_SECRET_STAGING }}"

      - name: Deploy to Azure Web App - Staging
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-micronectar-staging'
          images: '${{ secrets.DOCKERHUB_USERNAME }}/micronectar-api:${{ github.sha }}'

      - name: Restart Staging App Service
        uses: azure/cli@v1
        with:
          inlineScript: |
            echo "Reiniciando o App Service de Staging para aplicar todas as mudanças..."
            az webapp restart --resource-group rg-micronectar-devops --name 'app-micronectar-staging'

  deploy-production:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Production App Settings
        uses: azure/cli@v1
        with:
          inlineScript: |
            az webapp config appsettings set --resource-group rg-micronectar-devops --name 'app-micronectar-prod' --settings \
              "WEBSITES_PORT=8080" \
              "SPRING_PROFILES_ACTIVE=production" \
              "DB_URL=${{ secrets.DB_URL_PROD }}" \
              "DB_USERNAME=${{ secrets.DB_USERNAME_PROD }}" \
              "DB_PASSWORD=${{ secrets.DB_PASSWORD_PROD }}" \
              "JWT_SECRET=${{ secrets.JWT_SECRET_PROD }}"

      - name: Deploy to Azure Web App - Production
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-micronectar-prod'
          images: '${{ secrets.DOCKERHUB_USERNAME }}/micronectar-api:${{ github.sha }}'

      - name: Restart Production App Service
        uses: azure/cli@v1
        with:
          inlineScript: |
            echo "Reiniciando o App Service de Produção para aplicar todas as mudanças..."
            az webapp restart --resource-group rg-micronectar-devops --name 'app-micronectar-prod'