name: Feature FLow

on:
  push:
    branches:
      - feature/**
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Criando Pull Request"
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          branch: example/patch
          title: 'Feature: ${{ github.ref_name }}'
          body: |
            Pull Request automático da branch `${{ github.ref_name }}`.
            Por favor, revise as alterações e faça o merge para develop.
          base: develop
            
            
